{"name": "переход в раздел «История заказов»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='История заказов']\"}\n  (Session info: chrome=122.0.6261.112); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000100c7c508 chromedriver + 3966216\n1   chromedriver                        0x0000000100c74a94 chromedriver + 3934868\n2   chromedriver                        0x00000001008f7da0 chromedriver + 277920\n3   chromedriver                        0x000000010093a394 chromedriver + 549780\n4   chromedriver                        0x0000000100972bf0 chromedriver + 781296\n5   chromedriver                        0x000000010092efb0 chromedriver + 503728\n6   chromedriver                        0x000000010092fa28 chromedriver + 506408\n7   chromedriver                        0x0000000100c416f0 chromedriver + 3725040\n8   chromedriver                        0x0000000100c45be4 chromedriver + 3742692\n9   chromedriver                        0x0000000100c2a1d8 chromedriver + 3629528\n10  chromedriver                        0x0000000100c466e0 chromedriver + 3745504\n11  chromedriver                        0x0000000100c1d550 chromedriver + 3577168\n12  chromedriver                        0x0000000100c64f40 chromedriver + 3870528\n13  chromedriver                        0x0000000100c650e4 chromedriver + 3870948\n14  chromedriver                        0x0000000100c74704 chromedriver + 3933956\n15  libsystem_pthread.dylib             0x00000001891fe034 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001891f8e3c thread_start + 8", "trace": "self = <test_login_profile.TestAuthProfileUser object at 0x10238cb20>, app = <application.Application object at 0x104193c40>, user_data = <test_date.user_data.UserData object at 0x102455340>\n\n    @allure.title('переход в раздел «История заказов»')\n    def test_goto_history_page(self, app, user_data):\n        app.base.open('/login')\n        app.login_page.login(user_data.EMAIL, user_data.PASSWORD)\n>       app.login_page.goto_history()\n\ntest/test_login_profile.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/login_page.py:17: in goto_history\n    self.click(ProfilePageLocators.ORDERS_HISTORY_AREA)\npages/base_page.py:19: in click\n    self.app.wd.find_element(*locator).click()\n.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:742: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:348: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x102455a30>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...0001891fe034 _pthread_start + 136\\\\n16  libsystem_pthread.dylib             0x00000001891f8e3c thread_start + 8\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='История заказов']\"}\nE         (Session info: chrome=122.0.6261.112); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       0   chromedriver                        0x0000000100c7c508 chromedriver + 3966216\nE       1   chromedriver                        0x0000000100c74a94 chromedriver + 3934868\nE       2   chromedriver                        0x00000001008f7da0 chromedriver + 277920\nE       3   chromedriver                        0x000000010093a394 chromedriver + 549780\nE       4   chromedriver                        0x0000000100972bf0 chromedriver + 781296\nE       5   chromedriver                        0x000000010092efb0 chromedriver + 503728\nE       6   chromedriver                        0x000000010092fa28 chromedriver + 506408\nE       7   chromedriver                        0x0000000100c416f0 chromedriver + 3725040\nE       8   chromedriver                        0x0000000100c45be4 chromedriver + 3742692\nE       9   chromedriver                        0x0000000100c2a1d8 chromedriver + 3629528\nE       10  chromedriver                        0x0000000100c466e0 chromedriver + 3745504\nE       11  chromedriver                        0x0000000100c1d550 chromedriver + 3577168\nE       12  chromedriver                        0x0000000100c64f40 chromedriver + 3870528\nE       13  chromedriver                        0x0000000100c650e4 chromedriver + 3870948\nE       14  chromedriver                        0x0000000100c74704 chromedriver + 3933956\nE       15  libsystem_pthread.dylib             0x00000001891fe034 _pthread_start + 136\nE       16  libsystem_pthread.dylib             0x00000001891f8e3c thread_start + 8\n\n.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py:229: NoSuchElementException"}, "steps": [{"name": "Открытие страницы", "status": "passed", "parameters": [{"name": "url", "value": "'/login'"}], "start": 1709995389197, "stop": 1709995391817}, {"name": "переход по клику на «Личный кабинет»", "status": "passed", "steps": [{"name": "Ввод текста", "status": "passed", "parameters": [{"name": "text", "value": "'kov290583@ya.ru'"}, {"name": "locator", "value": "('xpath', \"//input[@name='name']\")"}], "start": 1709995391818, "stop": 1709995391924}, {"name": "Ввод текста", "status": "passed", "parameters": [{"name": "text", "value": "'121212'"}, {"name": "locator", "value": "('xpath', \"//input[@name='Пароль']\")"}], "start": 1709995391924, "stop": 1709995391952}, {"name": "Кликаем по кнопке", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//button[text()='Войти']\")"}], "start": 1709995391952, "stop": 1709995391977}], "parameters": [{"name": "name", "value": "'kov290583@ya.ru'"}, {"name": "password", "value": "'121212'"}], "start": 1709995391818, "stop": 1709995391977}, {"name": "переход в раздел «История заказов»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='История заказов']\"}\n  (Session info: chrome=122.0.6261.112); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000100c7c508 chromedriver + 3966216\n1   chromedriver                        0x0000000100c74a94 chromedriver + 3934868\n2   chromedriver                        0x00000001008f7da0 chromedriver + 277920\n3   chromedriver                        0x000000010093a394 chromedriver + 549780\n4   chromedriver                        0x0000000100972bf0 chromedriver + 781296\n5   chromedriver                        0x000000010092efb0 chromedriver + 503728\n6   chromedriver                        0x000000010092fa28 chromedriver + 506408\n7   chromedriver                        0x0000000100c416f0 chromedriver + 3725040\n8   chromedriver                        0x0000000100c45be4 chromedriver + 3742692\n9   chromedriver                        0x0000000100c2a1d8 chromedriver + 3629528\n10  chromedriver                        0x0000000100c466e0 chromedriver + 3745504\n11  chromedriver                        0x0000000100c1d550 chromedriver + 3577168\n12  chromedriver                        0x0000000100c64f40 chromedriver + 3870528\n13  chromedriver                        0x0000000100c650e4 chromedriver + 3870948\n14  chromedriver                        0x0000000100c74704 chromedriver + 3933956\n15  libsystem_pthread.dylib             0x00000001891fe034 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001891f8e3c thread_start + 8\n\n", "trace": "  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/pages/login_page.py\", line 17, in goto_history\n    self.click(ProfilePageLocators.ORDERS_HISTORY_AREA)\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/pages/base_page.py\", line 19, in click\n    self.app.wd.find_element(*locator).click()\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 742, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Кликаем по кнопке", "status": "passed", "parameters": [{"name": "locator", "value": "('xpath', \"//p[text() = 'Личный Кабинет']\")"}], "start": 1709995391977, "stop": 1709995392012}, {"name": "Кликаем по кнопке", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//a[text()='История заказов']\"}\n  (Session info: chrome=122.0.6261.112); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n0   chromedriver                        0x0000000100c7c508 chromedriver + 3966216\n1   chromedriver                        0x0000000100c74a94 chromedriver + 3934868\n2   chromedriver                        0x00000001008f7da0 chromedriver + 277920\n3   chromedriver                        0x000000010093a394 chromedriver + 549780\n4   chromedriver                        0x0000000100972bf0 chromedriver + 781296\n5   chromedriver                        0x000000010092efb0 chromedriver + 503728\n6   chromedriver                        0x000000010092fa28 chromedriver + 506408\n7   chromedriver                        0x0000000100c416f0 chromedriver + 3725040\n8   chromedriver                        0x0000000100c45be4 chromedriver + 3742692\n9   chromedriver                        0x0000000100c2a1d8 chromedriver + 3629528\n10  chromedriver                        0x0000000100c466e0 chromedriver + 3745504\n11  chromedriver                        0x0000000100c1d550 chromedriver + 3577168\n12  chromedriver                        0x0000000100c64f40 chromedriver + 3870528\n13  chromedriver                        0x0000000100c650e4 chromedriver + 3870948\n14  chromedriver                        0x0000000100c74704 chromedriver + 3933956\n15  libsystem_pthread.dylib             0x00000001891fe034 _pthread_start + 136\n16  libsystem_pthread.dylib             0x00000001891f8e3c thread_start + 8\n\n", "trace": "  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/pages/base_page.py\", line 19, in click\n    self.app.wd.find_element(*locator).click()\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 742, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/oleg/Documents/Practicum/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "('xpath', \"//a[text()='История заказов']\")"}], "start": 1709995392013, "stop": 1709995402046}], "start": 1709995391977, "stop": 1709995402047}], "parameters": [{"name": "app", "value": "'chrome'"}], "start": 1709995389197, "stop": 1709995402047, "uuid": "6a5a1e9f-7274-416a-ac9e-d0a7174abe72", "historyId": "06d78b40cc3750c17fb94d06cfed8fcd", "testCaseId": "265cb570c032ba9457691a5f45d72b16", "fullName": "test.test_login_profile.TestAuthProfileUser#test_goto_history_page", "labels": [{"name": "epic", "value": "Личный кабинет"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_profile"}, {"name": "subSuite", "value": "TestAuthProfileUser"}, {"name": "host", "value": "MacBook-Pro-Oleg.local"}, {"name": "thread", "value": "19478-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_profile"}]}